train:
  training:
    lr: 0.0001
    epochs: 10
    patience: 3
    accumulation_steps: 4
    hard_negatives_per_anchor: 1
    top_k: 10
  dataloader:
    batch_size: 32
    shuffle: True
    num_workers: auto
    pin_memory: True
  lora:
    lora8:
      r: 8
      lora_alpha: 16
      dropout: 0.1
      vision_layers: [8, 9, 10, 11]
      text_layers: [6, 7, 8, 9, 10, 11]
      projections: ['q_proj', 'k_proj']
    lora16:
      r: 16
      lora_alpha: 32
      dropout: 0.1
      vision_layers: [8, 9, 10, 11]
      text_layers: [6, 7, 8, 9, 10, 11]
      projections: ['q_proj', 'k_proj']
eval: &eval_params    # boilerplate
  dataloader:
    batch_size: 32
    shuffle: False
    num_workers: auto
    pin_memory: True
val: *eval_params
test: *eval_params